// Demo-only client-side data. Shared online editing will be connected in the next setup step.
let mineTimer=null,mineSeconds=0,mineStarted=false,mineCells=[];
function newMines(){clearInterval(mineTimer);mineSeconds=0;mineStarted=false;document.getElementById('mineTime').textContent=0;const grid=document.getElementById('mineGrid');grid.innerHTML='';mineCells=[];let mines=new Set();while(mines.size<10)mines.add(Math.floor(Math.random()*64));for(let i=0;i<64;i++){let b=document.createElement('button');b.dataset.mine=mines.has(i);b.onclick=()=>openMine(b,i,mines);grid.appendChild(b);mineCells.push(b)}document.getElementById('mineCount').textContent=10}
function openMine(b,i,mines){if(!mineStarted){mineStarted=true;mineTimer=setInterval(()=>{mineSeconds++;document.getElementById('mineTime').textContent=mineSeconds},1000)}if(b.classList.contains('open'))return;if(mines.has(i)){b.classList.add('mine');b.textContent='×';mineCells.forEach(x=>{if(x.dataset.mine){x.classList.add('mine');x.textContent='×'}});clearInterval(mineTimer);return}b.classList.add('open');let r=Math.floor(i/8),c=i%8,n=0;for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){let rr=r+dr,cc=c+dc;if(rr>=0&&rr<8&&cc>=0&&cc<8&&mines.has(rr*8+cc))n++}b.textContent=n||''}
const wordAnswer=()=>localStorage.getItem('dcWord')||'CREATE';let guess='',row=0;
function initWordle(){const rows=document.getElementById('wordRows');rows.innerHTML='';for(let r=0;r<6;r++){let rw=document.createElement('div');rw.className='word-row';for(let c=0;c<6;c++){let x=document.createElement('div');x.className='letter';x.id=`w${r}${c}`;rw.appendChild(x)}rows.appendChild(rw)}let keys='QWERTYUIOPASDFGHJKLZXCVBNM';document.getElementById('keyboard').innerHTML=keys.split('').map(k=>`<button class="key" onclick="keyWord('${k}')">${k}</button>`).join('')+`<button class="key" onclick="keyWord('⌫')">⌫</button><button class="key" onclick="submitWord()">ENTER</button>`}
function keyWord(k){if(k==='⌫'){guess=guess.slice(0,-1)}else if(guess.length<6)guess+=k;drawGuess()}
function drawGuess(){for(let c=0;c<6;c++)document.getElementById(`w${row}${c}`).textContent=guess[c]||''}
function submitWord(){if(guess.length!==6){document.getElementById('wordMessage').textContent='Use 6 letters.';return}let ans=wordAnswer().toUpperCase();for(let c=0;c<6;c++){let el=document.getElementById(`w${row}${c}`),ch=guess[c];el.classList.add(ch===ans[c]?'correct':ans.includes(ch)?'present':'absent')}if(guess===ans){document.getElementById('wordMessage').textContent='Solved.';return}row++;guess='';if(row>=6){document.getElementById('wordMessage').textContent='The word was '+ans+'.';return}drawGuess()}
function submitIdea(e){e.preventDefault();let a=JSON.parse(localStorage.getItem('dcIdeas')||'[]');a.push({type:ideaType.value,text:ideaText.value});localStorage.setItem('dcIdeas',JSON.stringify(a));ideaText.value='';ideaStatus.textContent='Thanks — your idea has been sent to the committee.'}
function loadChallenge(){let d=JSON.parse(localStorage.getItem('dcChallenge')||'{}');if(!d.topic)return;let h=document.querySelector('.challenge h3'),p=document.querySelector('.challenge p');if(h)h.textContent=d.topic;if(p&&d.desc)p.textContent=d.desc;document.querySelectorAll('.step').forEach((x,i)=>x.classList.toggle('active',i===Number(d.stage||0)));let s=document.querySelector('.challenge-meta strong:last-child');if(s)s.textContent=['Think','Design','Create','Present'][Number(d.stage||0)]}
document.addEventListener('DOMContentLoaded',()=>{newMines();initWordle();loadChallenge()});
